# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securewebapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='aes_encrypted_file',
            field=models.FileField(blank=True, null=True, upload_to='aes_encrypted_files'),
        ),
    ]
