# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-18 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import securewebapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('securewebapp', '0002_extenduser_aes_encrypted_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='submitted_file',
            field=models.FileField(blank=True, null=True, upload_to=securewebapp.models.content_file_name),
        ),
    ]
